package khu.rbecs.database;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

public class Main {
    public static void main(String... args) throws Exception {
        // JDBC
        // 1. DriverManager
        // 2. Connection
        // 3. Statement
        // 4. ResultSet
        String jdbc = "jdbc:h2:file:~/testdb1";
        String user = "sa";
        String password = "sa";
        try (var con = DriverManager.getConnection(jdbc, user, password)) {
            var statement = con.createStatement();
            statement.executeUpdate("""
                    create table if not exists users(
                        id int generated by default as identity,
                        name varchar(255),
                        primary key(id)
                    )
                    """);
            System.out.println("table created");
//            int rows = statement.executeUpdate("""
//                    insert into users(name)
//                    values ('Alice'),
//                           ('Bob'),
//                           ('Charlie');
//                    """);
//            System.out.println("Inserted " + rows + " rows");
            int id;
            String[] names = {"Alice", "Bob",
                    "Charli');delete from users where name='Alice';insert into users(name) values ('Alice"};
            for (String name : names) {
//                id = insert(statement, name);
                id = safeInsert(con, name);
                System.out.println("id = " + id + " name = " + name);
            }

            System.out.println("***");

            printUsers(statement);

            System.out.println("***");
            deleteById(con, 1);
            deleteById(con, 2);
            printUsers(statement);
        }
    }

    private static void printUsers(Statement statement) throws SQLException {
        var resultSet = statement.executeQuery("""
                select id, name from users
                """);
        while (resultSet.next()) {
            System.out.print("id: " + resultSet.getInt("id"));
            System.out.println(" name: " + resultSet.getString("name"));
        }
    }

    static int safeInsert(Connection con, String name) throws Exception {
        try (var st = con.prepareStatement("""
                        insert into users(name) values (?);""",
                Statement.RETURN_GENERATED_KEYS)
        ) {
            st.setString(1, name);
            st.executeUpdate();
            var rs = st.getGeneratedKeys();
            if (rs.next()) {
                return rs.getInt(1);
            } else {
                return -1;
            }
        }
    }

    static int insert(Statement st, String name) throws Exception {
        st.executeUpdate("""
                        insert into users(name)
                        values (%s);
                        """.formatted(
                        st.enquoteLiteral(name)
                ),
                Statement.RETURN_GENERATED_KEYS);
        var rs = st.getGeneratedKeys();
        if (rs.next()) {
            return rs.getInt(1);
        } else {
            return -1;
        }
    }

    static boolean deleteById(Connection con, int id) throws Exception {
        var st = con.prepareStatement("delete from USERS where id = ?;");
        st.setInt(1, id);
        return st.executeUpdate() > 0;
    }
}
